apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
  namespace: bank-app
data:
  MONGO_DB: bank
  REDIS_HOST: redis-ha-haproxy.bank-data.svc
  KAFKA_BOOTSTRAP: bank-kafka-kafka-bootstrap.bank-data.svc:9092
  KAFKA_TOPIC: transfer-events
